language: cpp
dist: trusty
addons:
  apt:
    sources:
    - llvm-toolchain-trusty-4.0
    packages:
    - clang-4.0
    - cmake
    - libsdl2-dev
    - libsdl2-image-dev
    - libsdl2-ttf-dev
env:
- MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
before_install:
- eval "${MATRIX_EVAL}"
script:
- cmake .
- make
after_success:
- openssl aes-256-cbc -K $encrypted_cecb146e247f_key -iv $encrypted_cecb146e247f_iv
  -in .snapcraft/travis_snapcraft.cfg -out .snapcraft/snapcraft.cfg -d
sudo: required
services:
- docker
deploy:
  'on':
    branch: master
  provider: script
  script: docker run -v $(pwd):$(pwd) -t snapcore/snapcraft sh -c "apt update -qq
    && cd $(pwd) && snapcraft && snapcraft push *.snap --release edge"
  skip_cleanup: true
