#ifndef ANIMATION_TYPE_HPP
#define ANIMATION_TYPE_HPP

enum AnimationType {
      ANIMATION_TYPE_EMPTY
    , ANIMATION_TYPE_WALL
    , ANIMATION_TYPE_DOOR
    , ANIMATION_TYPE_TELEPORTER_RED
    , ANIMATION_TYPE_TELEPORTER_GREEN
    , ANIMATION_TYPE_TELEPORTER_BLUE
    , ANIMATION_TYPE_CONVEY_UP
    , ANIMATION_TYPE_CONVEY_DOWN
    , ANIMATION_TYPE_CONVEY_LEFT
    , ANIMATION_TYPE_CONVEY_RIGHT
    , ANIMATION_TYPE_KEY
    , ANIMATION_TYPE_PUMPKIN
    , ANIMATION_TYPE_TITLE_SCREEN_KEY
    , ANIMATION_TYPE_ARROW_UP
    , ANIMATION_TYPE_ARROW_DOWN
    , ANIMATION_TYPE_COUNT
};

#endif
