#ifndef ANIMATIONTYPE_H
#define ANIMATIONTYPE_H

enum AnimationType {
	  ANIMATION_TYPE_CONVEY_UP
	, ANIMATION_TYPE_CONVEY_DOWN
	, ANIMATION_TYPE_CONVEY_LEFT
	, ANIMATION_TYPE_CONVEY_RIGHT
};

#endif//ANIMATIONTYPE_H
