#ifndef TILETYPE_H
#define TILETYPE_H

enum TileType {
	  TILETYPE_EMPTY
	, TILETYPE_WALL
	, TILETYPE_DOOR
	, TILETYPE_TELEPORTER_RED
	, TILETYPE_TELEPORTER_GREEN
	, TILETYPE_TELEPORTER_BLUE
	, TILETYPE_CONVEY_UP
	, TILETYPE_CONVEY_DOWN
	, TILETYPE_CONVEY_LEFT
	, TILETYPE_CONVEY_RIGHT
	, TILETYPE_COUNT
};

#endif//TILETYPE_H
